<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ToursApplication.Domain\ToursApplication.Domain.csproj" />
      <ProjectReference Include="..\ToursApplication.Repository\ToursApplication.Repository.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.15" />
      <PackageReference Include="Quartz" Version="3.18.1" />
    </ItemGroup>

</Project>
