<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>aspnet-ToursApplication.Web-7dc81e7b-aa42-497f-a719-08fe6d87d38f</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <None Update="app.db" CopyToOutputDirectory="PreserveNewest" ExcludeFromSingleFile="true"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Evolve" Version="3.2.0" />
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="9.0.7"/>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.7"/>
        <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="9.0.7"/>
        <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.7" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.7"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.7"/>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.15" />
        <PackageReference Include="Quartz" Version="3.18.1" />
        <PackageReference Include="Quartz.Extensions.Hosting" Version="3.18.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ToursApplication.Repository\ToursApplication.Repository.csproj" />
      <ProjectReference Include="..\ToursApplication.Service\ToursApplication.Service.csproj" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Views\Home\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Home\Privacy.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Shared\Error.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Shared\_Layout.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Shared\_LoginPartial.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Shared\_ValidationScriptsPartial.cshtml" />
      <_ContentIncludedByDefault Remove="Views\_ViewImports.cshtml" />
      <_ContentIncludedByDefault Remove="Views\_ViewStart.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\_ViewStart.cshtml" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Controllers\" />
      <Folder Include="Database\Migrations\" />
    </ItemGroup>

</Project>
